from typing import Protocol, Any


class Comparable(Protocol):
    def __lt__(self, other: Any, /) -> bool: ...
    def __eq__(self, other: Any, /) -> bool: ...


class Hashable(Protocol):
    def __hash__(self) -> int: ...
    def __eq__(self, other: Any, /) -> bool: ...
